example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist, show_json, show_html, show_watchlist_index, show_xml

app_name ="mywatchlist"
urlpatterns = [
    path('', show_watchlist_index, name="show_watchlist_index"),
    path('json', show_json, name="show_json"),
    path('xml', show_xml, name="show_xml"),
    path('html', show_watchlist,name="show_html"),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create-task'),
    path('hapus/<int:pk>', hapus_task, name='hapus-task'),
    path('add/', add_task, name='add_task'),
    path('change-status/<int:pk>', change_status, name='change-status'),
    path('json', show_json, name='show_json'),
]

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.
class MyWatchlist(models.Model):
    watched = models.BooleanField(default=False)
    title = models.CharField(max_length=100)
    # Create rating from 1-5
    rating = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null=False, blank=False,auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from dataclasses import fields
from django import forms
from todolist.models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = {'title', 'description'}

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem
# TODO: Create your views here.
def show_katalog(request):
  data_katalog = CatalogItem.objects.all()
  context = {
    'list_katalog': data_katalog,
    'name': 'Rafinal Haryokusumo Taloputra',
    'id': '2106634540',
  }
  return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from mywatchlist.models import MyWatchlist
# Create your views here.


def show_watchlist_index(request):
    data_watchlist = MyWatchlist.objects.all()
    watched_count = 0
    unwatched_count = 0
    res = False

    for item in data_watchlist:
        if item.watched:
            watched_count += 1
        else:
            unwatched_count += 1
    if watched_count > unwatched_count:
        res = True

    context = {
        'is_watched_more': res,
    }

    return render(request, 'watchlist_bonus.html', context)


def show_watchlist(request):
    watchlist = MyWatchlist.objects.all()
    context = {
        'watchlist': watchlist,
        'nama': 'Rafinal Haryokusumo Taloputra',
        'id': '2106634540'
    }
    return render(request, 'watchlist.html', context)


def show_xml(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize('xml', data), content_type='application/xml')


def show_json(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')


def show_html(request):
    data = MyWatchlist.objects.all()
    return HttpResponse(serializers.serialize('html', data), content_type='application/html')

todolist/views.py
import datetime
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.core import serializers

from todolist.forms import TaskForm
from .models import Task


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('todolist:login')


@login_required(login_url='/todolist/login/')
def show_todolist(request):
    try:
        user = request.user
        data = Task.objects.filter(user=user)
        context = {
            'todolist': data,
            'nama': user.username,
            'last_login': request.COOKIES['last_login'],
        }
        return render(request, "todolist.html", context)
    except KeyError:
        return redirect('todolist:login')


@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)

        form.instance.user = request.user
        form.instance.date = datetime.datetime.now()

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("todolist:show_todolist"))

    else:
        form = TaskForm()

        return render(request, 'create-task.html', {'form': form})


@login_required(login_url='/todolist/login/')
def hapus_task(request, pk):
    Task.objects.filter(id=pk).first().delete()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))


@login_required(login_url='/todolist/login/')
def change_status(request, pk):
    task = Task.objects.filter(id=pk).first()
    task.is_finished = task.is_finished ^ True
    task.save()
    return HttpResponse(b"CHANGED", status=201)


@login_required(login_url='/todolist/login/')
def show_json(request):
    user = request.user
    data = Task.objects.filter(user=user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


@login_required(login_url='/todolist/login/')
def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)

        form.instance.user = request.user
        form.instance.date = datetime.datetime.now()

        if form.is_valid():
            form.save()
            return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{name}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for katalog in list_katalog %}
        <tr>
            <th>{{katalog.item_name}}</th>
            <th>{{katalog.item_price}}</th>
            <th>{{katalog.item_stock}}</th>
            <th>{{katalog.rating}}</th>
            <th>{{katalog.description}}</th>
            <th>{{katalog.item_url}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %} {% block content %}
<h1>My Watchlist</h1>
<h5>Name:</h5>
<p>{{nama}}</p>

<h5>Student ID:</h5>
<p>{{id}}</p>

<table>
  <tr>
    <th>Watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release Date</th>
    <th>Review</th>
  </tr>
  {% for movie in watchlist %}
  <tr>
    <td style="text-align: center">
      {% if movie.watched %}
      <input type="checkbox" disabled checked />
      {% else %}
      <input type="checkbox" disabled />
      {% endif %}
    </td>
    <td style="padding: 10px">{{movie.title}}</td>
    <td style="text-align: center">{{movie.rating}}</td>
    <td style="padding: 10px">{{movie.release_date}}</td>
    <td style="padding: 10px">{{movie.review}}</td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

mywatchlist/templates/watchlist_bonus.html
{% extends 'base.html' %} {% block content %}

<div>
  <div>
    <h2 style="text-align: center">My Watchlist</h2>
    {% if is_watched_more %}
    <h3 style="text-align: center">Selamat, kamu sudah banyak menonton!</h3>
    {% else %}
    <h3>Wah, kamu masih sedikit menonton!</h3>
    {% endif %}
    <div style="text-align: center">
      <button onclick="location.href='/mywatchlist/html'">HTML</button>
      <button onclick="location.href='/mywatchlist/xml'">XML</button>
      <button onclick="location.href='/mywatchlist/json'">JSON</button>
    </div>
  </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    {% block meta %} {% endblock meta %}
  </head>

  <body>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    {% block content %} {% endblock content %}
  </body>
</html>

todolist/templates/create-task.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}

<link href="{% static 'style1.css' %}" rel="stylesheet">

{% if user.is_authenticated %} 

    <body class="text-center">
        <form class="form-signin w-100 m-auto" method="POST">

            {% csrf_token %}
            <h1 class="h3 mb-4 fw-normal" style="font-family: 'Courier New', monospace;">Create a Task</h1>

            <div class="form-floating">
                <input type="text" name="title" placeholder="title" class="form-control">
                <label for="floatingInput">Title</label>
            </div>
            <br>
            <div class="form-floating">
                <input type="description" name="description" placeholder="Description" class="form-control">
                <label for="floatingDescription">Description</label>
            </div>

            <input class="w-100 btn btn-lg btn-primary mt-5" type="submit" value="Create"></td>
        </form>
    </body>

    {% if messages %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}     

{% else %}

    You are not logged in.

{% endif %}

{% endblock %}

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
   
<link href="{% static 'style1.css' %}" rel="stylesheet">

<body class="text-center">

    <form class="form-signin w-100 m-auto" method="POST" action="">
        {% csrf_token %}
        <h1 class="h3 mb-4 fw-normal" style="font-family: 'Courier New', monospace;">Log in</h1>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger">
                        <strong>{{ message|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-floating">
            <input type="text" name="username" placeholder="Username" class="form-control">
            <label for="floatingInput">Username</label>
        </div>
        <br>
        <div class="form-floating">
            <input type="password" name="password" placeholder="Password" class="form-control">
            <label for="floatingPassword">Password</label>
        </div>

        <div class="mb-3">
            <label>
                Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
            </label>
        </div>

        <input class="w-100 btn btn-lg btn-primary" type="submit" value="Login"></td>

    </form>
</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}

<link href="{% static 'style1.css' %}" rel="stylesheet">

<body class="text-center"> 

    <form class="form-register w-100 m-auto" method="POST">

        {% csrf_token %}
        <h1 style="font-family: 'Courier New', monospace;">Registrasi Akun</h1>

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %} 
                <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                </div>
                {% endfor %}
            {% endfor %}
        {% endif %}

        <div class="form-floating my-3">
            <input type="text" name="username" placeholder="Username" class="form-control">
            <label for="floatingInput">Username</label>
            <small class='text-muted'>{{ form.username.help_text }}</small>
        </div>

        <div class="form-floating">
            <input type="password" name="password1" placeholder="Password" class="form-control">
            <label for="floatingInput">Password</label>
            <small class='text-muted'>{{ form.password1.help_text }}</small>
        </div>

        <div class="form-floating mb-3">
            <input type="password" name="password2" placeholder="Password" class="form-control">
            <label for="floatingInput">Re-Enter Password</label>
        </div>

        <div class="mb-3">
            <label>
                Sudah mempunyai akun? <a href="{% url 'todolist:login' %}">Log in</a>
            </label>
        </div>

        <input class="w-100 btn btn-lg btn-primary" type="submit" value="Register"></td>       

    </form>

</body>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link href="{% static 'style2.css' %}" rel="stylesheet">

<header>
    <div class="navbar navbar-light bg-warning shadow-sm">
      <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center" style="font-family: 'Courier New', monospace;">
          <strong> {{nama}}'s To-do List</strong>
        </a>
        <span class="navbar-text  ms-auto mx-4">Last login: {{ last_login }}</span>
        <a class="btn btn-outline-danger" href="{% url 'todolist:logout' %}">Logout</a>
      </div>
    </div>
</header>
  
<main>  
    <div class="album py-5 bg-light">
      <div class="container">

        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal1">
          Create a Task
        </button>

        <div class="modal fade" id="modal1" tabindex="-1" aria-labelledby="modal1Label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="modal1Label">Create Task</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form id="form" class="form-signin w-100 m-auto" method="POST">

                  {% csrf_token %}

                  <div class="form-floating mb-2">
                      <input type="text" name="title" placeholder="Title" class="form-control">
                      <label for="floatingInput">Title</label>
                  </div>

                  <div class="form-floating">
                      <textarea type="description" name="description" placeholder="Description" class="form-control" rows="3"></textarea>
                      <label for="floatingDescription">Description</label>
                  </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button id="button" type="button" class="btn btn-primary" type="submit" data-bs-dismiss="modal" value="Post">Post</button>
              </div>
              </form>
              </div>

            </div>
          </div>
        </div>

        <div id="tasks" class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mt-3"></div>

        </div>
</main>

<script>
  async function getTodolist() {
    return fetch("{% url 'todolist:show_json' %}").then((result) => result.json())
  }

  async function refreshTodolist(){
    document.getElementById("tasks").innerHTML = ""
    const todolist = await getTodolist()
    let htmlstring = ``
    todolist.forEach((task) => {
      htmlstring +=
      `
      <div class="col">
            <div class="card shadow-sm">
              <div class="card-body">
                <small class="text-muted">${task.fields.date}</small>
                <div class="d-flex justify-content-between align-items-center">
                    <h3 class="card-text mb-3">${task.fields.title}</h3>
      `
      if (task.fields.is_finished) {
        htmlstring += `                        <h3 class="text-success">✅</h3>`
      }
      htmlstring += `
                </div>
                <p class="card-text">${task.fields.description}</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
      `
      if (task.fields.is_finished) {
        htmlstring +=`
          <a onclick=changeStatus(${task.pk}) class="btn btn-sm btn-outline-secondary">Undo Task</a>
        `
      }
      else {
        htmlstring += `
          <a onclick=changeStatus(${task.pk}) class="btn btn-sm btn-outline-success">Mark Done</a>
        `
      }
      htmlstring += `
                    <a class="btn btn-sm btn-outline-danger" onclick=deleteTodolist(${task.pk})>Delete</a>   
                  </div>
                </div>
              </div>
            </div>
          </div>
      `
    })
    document.getElementById("tasks").innerHTML = htmlstring
  }

  function addTodolist() {
    fetch("{% url 'todolist:add_task' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshTodolist)
      document.getElementById("form").reset()
    return false
  }

  function changeStatus(id) {
    fetch("{{ request.path }}change-status/"+id).then(refreshTodolist)
    return false
  }

  function deleteTodolist(id) {
    fetch("{{ request.path }}hapus/"+id).then(refreshTodolist)
    return false
  }

  document.getElementById("button").onclick = addTodolist

  refreshTodolist()
</script>

{% endblock content %}